import "./IERC721Collectible";

/**
 * @title IERC721Collectible
 * @dev An ERC-721 Non-Fungible Token where each token is one of an enumerable
 * set of "types." Each token type has with a value (that may or may not correspond to
 * purchase / sale price; e.g. it may be "mining power"). The total value owned
 * by an address may be queried, as well as the number of types owned and list of
 * tokens by type. Types are enumerated 0...n-1.
 */
pragma solidity ^0.8.0;
interface IERC721CollectibleMintable is IERC721Collectible {
    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     */
    function mint(address to, uint256 type) external;
}
